name: Run UI tests and build test report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run UI tests
#        run: pytest tests/ -n 3 --alluredir=allure-results --clean-alluredir
        run: pytest tests/ -n 3

  build_and_publish_report:
    needs: run_tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
#        uses: simple-elf/allure-report-action@v1.7
#        if: always()
#        with:
#          gh_pages: gh-pages
#          allure_history: allure-history
#          allure_results: allure-results
        uses: simple-elf/allure-report-action@1.9
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
