name: Run UI tests and build test report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install -r requirements.txt

#      - name: Create directory for test results
#        run: mkdir -p allure-results/

      - name: Run UI tests
#        run: pytest tests/ -n 3 --alluredir=allure-results --clean-alluredir
#        run: pytest tests/ -n 3
        run: pytest tests/ -n 3 --alluredir=allure-results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: allure-results/

      - name: Display structure of uploaded files
        run: ls -R allure-results/

  load_history:
    needs: run_tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
  
  build_report:
    needs: run_tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test_results
          path: allure-results/

      - name: Display structure of downloaded files
        run: ls -R allure-results/
        
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          allure_report: allure-report
  
  publish_report:
    needs: [run_tests, build_report]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
