name: Run UI tests and build test report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run UI tests
        run: pytest tests/ -n 3 --alluredir=allure-results --clean-alluredir

  load_history:
    runs-on: ubuntu-24.04
    steps:
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: test_report
          path: test_report

  build_report:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: test_report
          allure_results: build/allure-results

  publish_report:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: test_report
          publish_dir: allure-history
